name: Wakatime

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: False
          SHOW_LOC_CHART: False
          SHOW_PROFILE_VIEWS: False
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
